# Generated by Django 4.0.4 on 2022-06-05 04:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inv', '0006_alter_categoria_descripcion'),
        ('cmp', '0002_comprasenc_compradet'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CompraDet',
            new_name='ComprasDet',
        ),
    ]
